const TIPO_INSTRUCCION = {
    COUT: 'INST_COUT',
    DECLARACION: 'DECLARACION',
    ASIGNACION: 'ASIGNACION',
    WHILE: 'WHILE',
    DEC_METODO: 'DEC_METODO',
    EXEC: 'EXEC',
    LLAMADA_METODO: 'LLAMADA_METODO',
    IF: 'IF',
    BREAK: 'BREAK'
}

module.exports = TIPO_INSTRUCCION